#How many customers are there?#

SELECT COUNT(*) AS total_customers
FROM customers;

#How many orders have been placed#
SELECT COUNT(*) AS total_orders
FROM orders;

#What is the total quantity of products sold?#
SELECT SUM(quantity) AS total_quantity_sold
FROM order_items;

#What is the average product price?#
SELECT ROUND(AVG(price), 2) AS average_product_price
FROM products;

#What are the different product categories?#
SELECT DISTINCT category
FROM products;

#What is the total revenue?#
SELECT
    SUM(p.price * oi.quantity) AS total_revenue
FROM order_items oi
JOIN products p
    ON oi.product_id = p.product_id;
    
 #Revenue generated by each product#   
 SELECT
    p.product_name,
    SUM(p.price * oi.quantity) AS revenue
FROM products p
JOIN order_items oi
    ON p.product_id = oi.product_id
GROUP BY p.product_id, p.product_name
ORDER BY revenue DESC;

#Which product generated the highest revenue?#
SELECT
    p.product_name,
    SUM(p.price * oi.quantity) AS revenue
FROM products p
JOIN order_items oi
    ON p.product_id = oi.product_id
GROUP BY p.product_id, p.product_name
ORDER BY revenue DESC
LIMIT 1;

#Revenue by category#
SELECT
    p.category,
    SUM(p.price * oi.quantity) AS revenue
FROM products p
JOIN order_items oi
    ON p.product_id = oi.product_id
GROUP BY p.category
ORDER BY revenue DESC;

#Which category generated the highest revenue?#
SELECT
    p.category,
    SUM(p.price * oi.quantity) AS revenue
FROM products p
JOIN order_items oi
    ON p.product_id = oi.product_id
GROUP BY p.category
ORDER BY revenue DESC
LIMIT 1;

#Products that have never been ordered#
SELECT
    p.product_id,
    p.product_name
FROM products p
LEFT JOIN order_items oi
    ON p.product_id = oi.product_id
WHERE oi.product_id IS NULL;


#Most expensive product in each category#

WITH ranked_products AS (
    SELECT
        product_name,
        category,
        price,
        RANK() OVER (
            PARTITION BY category
            ORDER BY price DESC
        ) AS rnk
    FROM products
)

SELECT
    product_name,
    category,
    price
FROM ranked_products
WHERE rnk = 1;

#Highest-selling product in each category#
WITH product_sales AS (
    SELECT
        p.product_name,
        p.category,
        SUM(oi.quantity) AS quantity_sold
    FROM products p
    JOIN order_items oi
        ON p.product_id = oi.product_id
    GROUP BY p.product_id, p.product_name, p.category
),
ranked_products AS (
    SELECT
        *,
        RANK() OVER (
            PARTITION BY category
            ORDER BY quantity_sold DESC
        ) AS rnk
    FROM product_sales
)

SELECT
    product_name,
    category,
    quantity_sold
FROM ranked_products
WHERE rnk = 1;

#Second-highest revenue-generating product#
WITH product_revenue AS (
    SELECT
        p.product_name,
        SUM(p.price * oi.quantity) AS revenue
    FROM products p
    JOIN order_items oi
        ON p.product_id = oi.product_id
    GROUP BY p.product_id, p.product_name
),
ranked_products AS (
    SELECT
        *,
        DENSE_RANK() OVER (ORDER BY revenue DESC) AS rnk
    FROM product_revenue
)

SELECT
    product_name,
    revenue
FROM ranked_products
WHERE rnk = 2;

#First order date of each customer#

SELECT
    c.customer_name,
    MIN(o.order_date) AS first_order_date
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.customer_name
ORDER BY first_order_date;
